name: flutter_portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.8
  carousel_slider: ^4.2.1
  get_it: ^7.2.0
  extended_image: ^6.3.4
  go_router: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/open-sans.ttf
    - family: abo
      fonts:
        - asset: assets/fonts/abo.ttf
    - family: dosis
      fonts:
        - asset: assets/fonts/dosis.ttf
