name: flutter_portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.2
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.10
  extended_image: ^6.3.4
  go_router: ^6.0.3
  dio: ^5.0.3
  flutter_hooks: ^0.18.6
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/open-sans.ttf
    - family: abo
      fonts:
        - asset: assets/fonts/abo.ttf
    - family: dosis
      fonts:
        - asset: assets/fonts/dosis.ttf
